truck_weight = int(input())
platform_height = int(input())
piano_weight = int(input())
piano_height = int(input())
fridge_weight = int(input())
fridge_height = int(input())
max_weight_on_the_bridge = int(input())
max_height_on_the_tunnel = int(input())

if max()